### ISSUE TITLE
Crash on every search

### ISSUE THREAD

**Issue by Zottelchen** [Garulf/Steam-Search#29]
[Crashlog.txt](https://github.com/Garulf/Steam-Search/files/8986967/2022-06-26.txt)

```
Exception:
System.IO.InvalidDataException: Steam Search|Traceback (most recent call last):
  File "C:\Users\Zottelchen\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Steam Search-4.1.1\run.py", line 9, in <module>
    from plugin.main import SteamSearch
  File "C:\Users\Zottelchen\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Steam Search-4.1.1\plugin\main.py", line 6, in <module>
    from flox import Flox, ICON_SETTINGS
  File "C:\Users\Zottelchen\scoop\apps\Flow-Launcher\current\app-1.9.3\UserData\Plugins\Steam Search-4.1.1\lib\flox\__init__.py", line 40, in <module>
    if str(APPDATA.joinpath(launcher_dir)) in str(CURRENT_WORKING_DIR):
  File "C:\Users\Zottelchen\scoop\apps\python\current\lib\pathlib.py", line 851, in joinpath
    return self._make_child(args)
  File "C:\Users\Zottelchen\scoop\apps\python\current\lib\pathlib.py", line 616, in _make_child
    drv, root, parts = self._parse_args(args)
  File "C:\Users\Zottelchen\scoop\apps\python\current\lib\pathlib.py", line 578, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I've set the trigger to * and entered my steam path, but it still crashes.

**Comment by Garulf** [comment]
I believe the code I use to find FLow Launcher on your system (so I can reference settings) is not written with scoop in mind and is failing. I'm working on a fix now.
