### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TheBoxTrot** [Garulf/Steam-Search#40]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Temp\onefile_10220_133173867251973512\flox\launcher.py", line 44, in run
  File "C:\Users\user\AppData\Local\Temp\onefile_10220_133173867251973512\flox\__init__.py", line 131, in _query
  File "C:\Users\user\AppData\Local\Temp\onefile_10220_133173867251973512\plugin\main.py", line 18, in query
  File "C:\Users\user\AppData\Local\Temp\onefile_10220_133173867251973512\plugin\steam.py", line 90, in all_games
  File "C:\Users\user\AppData\Local\Temp\onefile_10220_133173867251973512\plugin\library.py", line 44, in games
KeyError: 'AppState'

```
</p>
</details>

**Comment by TheStxfan** [comment]
I have this error too

**Comment by TheStxfan** [comment]
Did you managed somehow to fix it?

**Comment by Garulf** [comment]
Looks like the plugin is having a hard time with on of your game's manifest file. I've updated The Plugin to skip these files instead of crashing. Please check for updates with `pm update` or manually install by typing: `pm install https://github.com/Garulf/Steam-Search/releases/download/v8.1.0/Steam-Search.zip`.

There is a new "Debug" option in the plugin settings when selected will log any files the plugin is having trouble reading.

![image](https://user-images.githubusercontent.com/535299/221008854-956962df-5c01-4e7d-87f5-7679ed2c833e.png)


If you'd liek to help me find out why these files are not working could you please enable debugging and upload your log and the file its having trouble with? I'd like to fix this error instead of skipping over them. Thanks in advanced!

**Comment by TheBoxTrot** [comment]
Would that possibly be caused by games that don't have a steam page or any metadata e.g beta games?

**Comment by Garulf** [comment]
Yes, this is very possible. But if possible I'd like to inspect the cause to make sure.

**Comment by TheBoxTrot** [comment]
Will do as soon as I can

**Comment by Garulf** [comment]
> Will do as soon as I can 

Awesome! I appreciate it.

**Comment by TheBoxTrot** [comment]
weird its now working with the new update ios this the file you need? 
[2023-02-24.txt](https://github.com/Garulf/Steam-Search/files/10822962/2023-02-24.txt)

**Comment by Garulf** [comment]
> weird its now working with the new update. 

Yeah instead of stopping when a games manifest's data is incomplete or missing it now skips the file. *But* it'll log which file it skips as long as you have debugging enabled.

> is this the file you need? [2023-02-24.txt](https://github.com/Garulf/Steam-Search/files/10822962/2023-02-24.txt)

Sorry I should have clarified which log file. There should be a log file in the plugins install directory called `plugin.log`.

![image](https://user-images.githubusercontent.com/535299/221225239-510efbea-c87d-4fa8-a5e4-a016cf5c07d2.png)

**Comment by Garulf** [comment]
Sorry for the delay, looks like I messed up and the debug is never triggered. 

Sorry about. When I find the time I'd like to fix your issue as soon as I can.

**Comment by Garulf** [comment]
Fixed with version 11:

https://github.com/user-attachments/assets/835cb86f-61d3-47ab-8c33-1f0c581958bb

https://github.com/Garulf/Steam-Search/releases/tag/v11.0.2
