### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TheStxfan** [Garulf/Steam-Search#41]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\Stefan\AppData\Local\Temp\onefile_4524_133206834863239524\flox\launcher.py", line 44, in run
  File "C:\Users\Stefan\AppData\Local\Temp\onefile_4524_133206834863239524\flox\__init__.py", line 131, in _query
  File "C:\Users\Stefan\AppData\Local\Temp\onefile_4524_133206834863239524\plugin\main.py", line 18, in query
  File "C:\Users\Stefan\AppData\Local\Temp\onefile_4524_133206834863239524\plugin\steam.py", line 90, in all_games
  File "C:\Users\Stefan\AppData\Local\Temp\onefile_4524_133206834863239524\plugin\library.py", line 44, in games
KeyError: 'name'

```
</p>
</details>

**Comment by Garulf** [comment]
Similar to #40
