### ISSUE TITLE
FileNotFoundError

### ISSUE THREAD

**Issue by ScarletEbinger** [Garulf/Steam-Search#47]
I searched the directory, it does not exist "grid" file or folder

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\flox\launcher.py", line 44, in run
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\flox\__init__.py", line 131, in _query
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\plugin\main.py", line 37, in query
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\functools.py", line 981, in __get__
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\plugin\library.py", line 128, in icon
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\plugin\library.py", line 121, in get_image
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\plugin\library.py", line 75, in get_image
  File "C:\Users\Scarl\AppData\Local\Temp\ONEFIL~1\pathlib.py", line 1017, in iterdir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Steam\\userdata\\124956862\\config\\grid'

```
</p>
</details>

**Comment by Garulf** [comment]
Do you have any "Non-Steam" games added to your Steam application?

**Comment by ScarletEbinger** [comment]
no

**Comment by Blazzycrafter** [comment]
i found out:
i dont have a file  of folder named grod inside the config folder
![image](https://i.imgur.com/JAmELQs.png)

**Comment by Garulf** [comment]
Please try version 9.0.1 when you can. It should fix this issue.
