### ISSUE TITLE
plugin crashes when starting

### ISSUE THREAD

**Issue by Sucaiking** [Garulf/Steam-Search#61]
I used zip file to install, and when i type st, it immediately crashes.

[2023-10-01.txt](https://github.com/Garulf/Steam-Search/files/12775777/2023-10-01.txt)
```
Flow Launcher version: 1.16.1
OS Version: 22621.2283
IntPtr Length: 8
x64: True

Python Path: C:\Python311\pythonw.exe
Node Path: 
Date: 10/01/2023 08:28:55
Exception:
Steam Search Exception: 
Websites: https://github.com/Garulf/Steam-Search
Author: Garulf
Version: 9.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\run.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\plugin\main.py", line 6, in <module plugin.main>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\flox\__init__.py", line 51, in <module flox>
FileNotFoundError: Unable to locate Launcher directory
Current working directory: E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\run.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\plugin\main.py", line 6, in <module plugin.main>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search\flox\__init__.py", line 51, in <module flox>
FileNotFoundError: Unable to locate Launcher directory
Current working directory: E:\Software\Flow-Launcher-Portable-1.10.1\FlowLauncher\app-1.16.1\Plugins\Steam-Search

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 291
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 296
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 311
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 193
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass139_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults(Boolean isReQuery) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 850
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

```

**Comment by MaskedRPGFan** [comment]
Fix is simple, you can not change name of the FlowLaucher directory to sth different from FlowLaucher. Flox lib is bugged and depends on this name.

**Comment by Garulf** [comment]
Fixed with version 11:

https://github.com/user-attachments/assets/835cb86f-61d3-47ab-8c33-1f0c581958bb

https://github.com/Garulf/Steam-Search/releases/tag/v11.0.2
