### ISSUE TITLE
"Steam library not found."

### ISSUE THREAD

**Issue by indigofairyx** [Garulf/Steam-Search#63]
ive never once go this to work. always get this same error. 

not sure what im missing. is there something in steam steams setting i need to toggle on??

![image](https://github.com/Garulf/Steam-Search/assets/126439010/2fbc2fec-1e91-4eff-86a5-b05a5ff25814)

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\CLOUDEN\AppData\Local\FLOWLA~1\APP-11~1.2\UserData\Plugins\STEAMS~1.1\flox\launcher.py", line 44, in run
  File "C:\Users\CLOUDEN\AppData\Local\FLOWLA~1\APP-11~1.2\UserData\Plugins\STEAMS~1.1\flox\__init__.py", line 135, in _context_menu
  File "C:\Users\CLOUDEN\AppData\Local\FLOWLA~1\APP-11~1.2\UserData\Plugins\STEAMS~1.1\plugin\main.py", line 50, in context_menu
TypeError: 'NoneType' object is not subscriptable

```
</p>
</details>

**Comment by Garulf** [comment]
Try the new version 11 and see if it works now

https://github.com/Garulf/Steam-Search/releases/tag/v11.0.2
