### ISSUE TITLE
Steam Search error: Failed to respond

### ISSUE THREAD

**Issue by gssadssd** [Garulf/Steam-Search#64]
[2024-06-02 logs.txt](https://github.com/user-attachments/files/15526112/2024-06-02.logs.txt)
this is the logs

this is the exception message:
Flow Launcher version: 1.18.0
OS Version: 19045.4412
IntPtr Length: 8
x64: True

Python Path: C:\Users\Asus\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.11.4\pythonw.exe
Node Path: 
Date: 06/02/2024 18:44:25
Exception:
Steam Search Exception: 
Websites: https://github.com/Garulf/Steam-Search
Author: Garulf
Version: 9.0.1
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Exception ignored in: <compiled_function Launcher.__del__ at 0x000002559539FA60>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\launcher.py", line 16, in __del__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\launcher.py", line 28, in run
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\functools.py", line 981, in __get__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\__init__.py", line 327, in settings
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\settings.py", line 11, in __init__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\settings.py", line 22, in _load
TypeError: 'NoneType' object is not iterable

 ---> System.IO.InvalidDataException: Exception ignored in: <compiled_function Launcher.__del__ at 0x000002559539FA60>
Traceback (most recent call last):
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\launcher.py", line 16, in __del__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\launcher.py", line 28, in run
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\functools.py", line 981, in __get__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\__init__.py", line 327, in settings
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\settings.py", line 11, in __init__
  File "C:\Users\Asus\AppData\Roaming\FLOWLA~1\Plugins\STEAMS~1.1\flox\settings.py", line 22, in _load
TypeError: 'NoneType' object is not iterable

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 243
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 248
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 196
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 230
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass23_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 224
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 307
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Should be fixed in latest version: https://github.com/Garulf/Steam-Search/releases/tag/v10.0.0
